/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import javax.swing.JOptionPane;
import sun.print.BackgroundLookupListener;

public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setExtendedState(6);
    }

    void new_Student() {
        New_Student create = new New_Student();

        create.setSize(1650, 1280);
        create.setLocation(0, 0);

        Panel_right.remove(this);
        Panel_right.add(create, BorderLayout.CENTER);
        Panel_right.setComponentZOrder(create, 0);
        Panel_right.revalidate();
        Panel_right.repaint();

    }

    void exit() {
        JOptionPane.showMessageDialog(this, "Hasta luego :D");
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        North_Panel = new javax.swing.JPanel();
        Left_Panel = new javax.swing.JPanel();
        Left_lbl = new javax.swing.JLabel();
        lbl_teachers = new javax.swing.JLabel();
        Lbl_Students = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Icon_sena = new javax.swing.JLabel();
        Lbl_Exit = new javax.swing.JLabel();
        Panel_right = new javax.swing.JPanel();
        Background_image = new javax.swing.JLabel();
        Lbl_Edusena = new javax.swing.JLabel();
        Ventana = new javax.swing.JDesktopPane();
        Menu_rapido = new javax.swing.JMenuBar();
        Menu_Archivo = new javax.swing.JMenu();
        Item_new = new javax.swing.JMenuItem();
        Item_exit = new javax.swing.JMenuItem();
        Menu_edit = new javax.swing.JMenu();
        Menu_help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        North_Panel.setBackground(new java.awt.Color(0, 173, 0));

        javax.swing.GroupLayout North_PanelLayout = new javax.swing.GroupLayout(North_Panel);
        North_Panel.setLayout(North_PanelLayout);
        North_PanelLayout.setHorizontalGroup(
            North_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1780, Short.MAX_VALUE)
        );
        North_PanelLayout.setVerticalGroup(
            North_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Background.add(North_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1780, -1));

        Left_Panel.setBackground(new java.awt.Color(0, 173, 0));
        Left_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Left_lbl.setBackground(new java.awt.Color(255, 255, 255));
        Left_lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Left_lbl.setForeground(new java.awt.Color(0, 173, 0));
        Left_lbl.setText("xxx");
        Left_lbl.setToolTipText("0");
        Left_lbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, java.awt.Color.yellow));
        Left_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Left_lbl.setOpaque(true);
        Left_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Left_lblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Left_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Left_lblMouseExited(evt);
            }
        });
        Left_Panel.add(Left_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 250, 70));

        lbl_teachers.setBackground(new java.awt.Color(255, 255, 255));
        lbl_teachers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_teachers.setForeground(new java.awt.Color(0, 173, 0));
        lbl_teachers.setText("Profesores");
        lbl_teachers.setToolTipText("0");
        lbl_teachers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lbl_teachers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_teachers.setOpaque(true);
        lbl_teachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_teachersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_teachersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_teachersMouseExited(evt);
            }
        });
        Left_Panel.add(lbl_teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 361, 250, 70));

        Lbl_Students.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_Students.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Lbl_Students.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Students.setText("Estudiantes");
        Lbl_Students.setToolTipText("0");
        Lbl_Students.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Lbl_Students.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_Students.setOpaque(true);
        Lbl_Students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_StudentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lbl_StudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lbl_StudentsMouseExited(evt);
            }
        });
        Left_Panel.add(Lbl_Students, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 173, 0));
        jLabel4.setText("Cursos");
        jLabel4.setToolTipText("0");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        Left_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 521, 250, 70));

        Icon_sena.setBackground(new java.awt.Color(0, 173, 0));
        Icon_sena.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Icon_sena.setForeground(new java.awt.Color(255, 255, 255));
        Icon_sena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon_sena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_sin_fondo-removebg-preview.png"))); // NOI18N
        Icon_sena.setText("EDUSENA");
        Icon_sena.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Icon_sena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Icon_sena.setIconTextGap(30);
        Icon_sena.setOpaque(true);
        Icon_sena.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Icon_sena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icon_senaMouseClicked(evt);
            }
        });
        Left_Panel.add(Icon_sena, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 183));

        Lbl_Exit.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_Exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Lbl_Exit.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Exit.setText("Exit");
        Lbl_Exit.setToolTipText("0");
        Lbl_Exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Lbl_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_Exit.setOpaque(true);
        Lbl_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lbl_ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lbl_ExitMouseExited(evt);
            }
        });
        Left_Panel.add(Lbl_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 603, 250, 70));

        Background.add(Left_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1310));

        Panel_right.setBackground(new java.awt.Color(255, 255, 255));
        Panel_right.setPreferredSize(new java.awt.Dimension(1600, 1310));

        Background_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N

        Lbl_Edusena.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Lbl_Edusena.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Edusena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Edusena.setText("EDUSENA");

        javax.swing.GroupLayout Panel_rightLayout = new javax.swing.GroupLayout(Panel_right);
        Panel_right.setLayout(Panel_rightLayout);
        Panel_rightLayout.setHorizontalGroup(
            Panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_rightLayout.createSequentialGroup()
                .addGap(591, 591, 591)
                .addGroup(Panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Background_image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Edusena, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(686, Short.MAX_VALUE))
        );
        Panel_rightLayout.setVerticalGroup(
            Panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_rightLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(Background_image, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_Edusena, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        Background.add(Panel_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 100, 1770, 1210));

        Ventana.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout VentanaLayout = new javax.swing.GroupLayout(Ventana);
        Ventana.setLayout(VentanaLayout);
        VentanaLayout.setHorizontalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1780, Short.MAX_VALUE)
        );
        VentanaLayout.setVerticalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );

        Background.add(Ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 1780, 1140));

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        Menu_rapido.setBackground(new java.awt.Color(0, 51, 90));
        Menu_rapido.setForeground(new java.awt.Color(255, 255, 255));
        Menu_rapido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Menu_Archivo.setText("File");

        Item_new.setText("New Student");
        Item_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_newActionPerformed(evt);
            }
        });
        Menu_Archivo.add(Item_new);

        Item_exit.setText("Exit");
        Item_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_exitActionPerformed(evt);
            }
        });
        Menu_Archivo.add(Item_exit);

        Menu_rapido.add(Menu_Archivo);

        Menu_edit.setText("Edit");
        Menu_rapido.add(Menu_edit);

        Menu_help.setText("Help");
        Menu_rapido.add(Menu_help);

        setJMenuBar(Menu_rapido);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_newActionPerformed
        // Create New Student
        //new_Student();

    }//GEN-LAST:event_Item_newActionPerformed

    private void Item_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_exitActionPerformed
        //Menu_item exit
        exit();

    }//GEN-LAST:event_Item_exitActionPerformed

    private void Left_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Left_lblMouseEntered
        // TODO add your handling code here:
        Left_lbl.setBackground(new Color(235, 235, 235));

    }//GEN-LAST:event_Left_lblMouseEntered

    private void Left_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Left_lblMouseExited
        // TODO add your handling code here:
        Left_lbl.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Left_lblMouseExited

    private void Left_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Left_lblMouseClicked
        // TODO add your handling code here:
        //new_Student();


    }//GEN-LAST:event_Left_lblMouseClicked

    private void Icon_senaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icon_senaMouseClicked

    }//GEN-LAST:event_Icon_senaMouseClicked

    private void Lbl_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_ExitMouseClicked
        exit();
    }//GEN-LAST:event_Lbl_ExitMouseClicked

    private void Lbl_StudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_StudentsMouseClicked
        Students list = new Students();
        
        list.setSize(1650, 1180);
        list.setLocation(0, 0);
        Panel_right.removeAll();
        Panel_right.add(list, BorderLayout.CENTER);
        Panel_right.setComponentZOrder(list, 0);
        Panel_right.revalidate();
        Panel_right.repaint();
    }//GEN-LAST:event_Lbl_StudentsMouseClicked

    private void Lbl_StudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_StudentsMouseEntered
        Lbl_Students.setBackground(new Color(235, 235, 235));
    }//GEN-LAST:event_Lbl_StudentsMouseEntered

    private void Lbl_StudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_StudentsMouseExited
        Lbl_Students.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Lbl_StudentsMouseExited

    private void Lbl_ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_ExitMouseEntered
        Lbl_Exit.setBackground(new Color(235, 235, 235));
    }//GEN-LAST:event_Lbl_ExitMouseEntered

    private void Lbl_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_ExitMouseExited
        Lbl_Exit.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Lbl_ExitMouseExited

    private void lbl_teachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_teachersMouseClicked
        Teachers teacher = new Teachers();

        teacher.setSize(1650, 1180);
        teacher.setLocation(0, 0);

        Panel_right.removeAll();
        Panel_right.add(teacher, BorderLayout.CENTER);
        Panel_right.setComponentZOrder(teacher, 0);
        Panel_right.revalidate();
        Panel_right.repaint();
    }//GEN-LAST:event_lbl_teachersMouseClicked

    private void lbl_teachersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_teachersMouseEntered
         lbl_teachers.setBackground(new Color(235, 235, 235));
    }//GEN-LAST:event_lbl_teachersMouseEntered

    private void lbl_teachersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_teachersMouseExited
       lbl_teachers.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_lbl_teachersMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Background_image;
    private javax.swing.JLabel Icon_sena;
    private javax.swing.JMenuItem Item_exit;
    private javax.swing.JMenuItem Item_new;
    private javax.swing.JLabel Lbl_Edusena;
    private javax.swing.JLabel Lbl_Exit;
    private javax.swing.JLabel Lbl_Students;
    private javax.swing.JPanel Left_Panel;
    private javax.swing.JLabel Left_lbl;
    private javax.swing.JMenu Menu_Archivo;
    private javax.swing.JMenu Menu_edit;
    private javax.swing.JMenu Menu_help;
    private javax.swing.JMenuBar Menu_rapido;
    private javax.swing.JPanel North_Panel;
    private javax.swing.JPanel Panel_right;
    private javax.swing.JDesktopPane Ventana;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_teachers;
    // End of variables declaration//GEN-END:variables
}
