/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Graficas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Aprendiz
 */
public class Crear extends javax.swing.JInternalFrame {

    JDesktopPane desktopPane = new JDesktopPane();

    public Crear() {
        initComponents();
        desktopPane.setBackground(Color.RED);
        
    }
    
    private void clean(){
        Txt_nameStudent.setText("");
        Txt_LastNameStudent.setText("");
        Txt_Day_Born.setText("");
        Box_grade.setSelectedIndex(1);
        Box_section.setSelectedIndex(1);
        Txt_Direction.setText("");
        Txt_telephone.setText("");
        Txt_email.setText("");
        Txt_password.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Input_panel = new javax.swing.JPanel();
        Lbl_Student = new javax.swing.JLabel();
        Lbl_Name1 = new javax.swing.JLabel();
        Txt_nameStudent = new javax.swing.JTextField();
        Lbl_LastName = new javax.swing.JLabel();
        Txt_LastNameStudent = new javax.swing.JTextField();
        Lbl_Born = new javax.swing.JLabel();
        Lbl_Format = new javax.swing.JLabel();
        Txt_Day_Born = new javax.swing.JTextField();
        Lbl_Document = new javax.swing.JLabel();
        Txt_DocumentStudent = new javax.swing.JTextField();
        Box_grade = new javax.swing.JComboBox<>();
        Lbl_Grade = new javax.swing.JLabel();
        Btn_Create = new javax.swing.JButton();
        Lbl_section = new javax.swing.JLabel();
        Box_section = new javax.swing.JComboBox<>();
        Lbl_Direction = new javax.swing.JLabel();
        Txt_Direction = new javax.swing.JTextField();
        Lbl_Telephone = new javax.swing.JLabel();
        Txt_telephone = new javax.swing.JTextField();
        Lbl_Email = new javax.swing.JLabel();
        Txt_email = new javax.swing.JTextField();
        Lbl_password = new javax.swing.JLabel();
        Txt_password = new javax.swing.JTextField();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1700, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Input_panel.setBackground(new java.awt.Color(255, 255, 255));
        Input_panel.setBorder(null);
        Input_panel.setPreferredSize(new java.awt.Dimension(1600, 650));

        Lbl_Student.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Lbl_Student.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Student.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Student.setText("Nuevo Estudiante");

        Lbl_Name1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Name1.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Name1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Name1.setText("Nombres");

        Txt_nameStudent.setBackground(new java.awt.Color(235, 235, 235));
        Txt_nameStudent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_nameStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_nameStudentMousePressed(evt);
            }
        });
        Txt_nameStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_nameStudentActionPerformed(evt);
            }
        });

        Lbl_LastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_LastName.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_LastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_LastName.setText("Apellidos");

        Txt_LastNameStudent.setBackground(new java.awt.Color(235, 235, 235));
        Txt_LastNameStudent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_LastNameStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_LastNameStudentMousePressed(evt);
            }
        });
        Txt_LastNameStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_LastNameStudentActionPerformed(evt);
            }
        });

        Lbl_Born.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Born.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Born.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Born.setText("Fecha de Nacimiento");

        Lbl_Format.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        Lbl_Format.setForeground(new java.awt.Color(153, 153, 153));
        Lbl_Format.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Format.setText("Formato: yyyy/MM/dd");

        Txt_Day_Born.setBackground(new java.awt.Color(235, 235, 235));
        Txt_Day_Born.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_Day_Born.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Day_BornMousePressed(evt);
            }
        });
        Txt_Day_Born.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Day_BornActionPerformed(evt);
            }
        });

        Lbl_Document.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Document.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Document.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Document.setText("N. Documento");

        Txt_DocumentStudent.setBackground(new java.awt.Color(235, 235, 235));
        Txt_DocumentStudent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_DocumentStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_DocumentStudentMousePressed(evt);
            }
        });
        Txt_DocumentStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DocumentStudentActionPerformed(evt);
            }
        });

        Box_grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"}));

        Lbl_Grade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Grade.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Grade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Grade.setText("Grado");

        Btn_Create.setBackground(new java.awt.Color(0, 173, 0));
        Btn_Create.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Create.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Create.setText("Crear");
        Btn_Create.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Btn_Create.setBorderPainted(false);
        Btn_Create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CreateActionPerformed(evt);
            }
        });

        Lbl_section.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_section.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_section.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_section.setText("Sección");

        Box_section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A", "B", "C", "D"}));

        Lbl_Direction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Direction.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Direction.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Direction.setText("Dirección");

        Txt_Direction.setBackground(new java.awt.Color(235, 235, 235));
        Txt_Direction.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_Direction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_DirectionMousePressed(evt);
            }
        });
        Txt_Direction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DirectionActionPerformed(evt);
            }
        });

        Lbl_Telephone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Telephone.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Telephone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Telephone.setText("Teléfono");

        Txt_telephone.setBackground(new java.awt.Color(235, 235, 235));
        Txt_telephone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_telephone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_telephoneMousePressed(evt);
            }
        });
        Txt_telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_telephoneActionPerformed(evt);
            }
        });

        Lbl_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Email.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Email.setText("Email");

        Txt_email.setBackground(new java.awt.Color(235, 235, 235));
        Txt_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_emailMousePressed(evt);
            }
        });
        Txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_emailActionPerformed(evt);
            }
        });

        Lbl_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_password.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_password.setText("Contraseña");

        Txt_password.setBackground(new java.awt.Color(235, 235, 235));
        Txt_password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_passwordMousePressed(evt);
            }
        });
        Txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Input_panelLayout = new javax.swing.GroupLayout(Input_panel);
        Input_panel.setLayout(Input_panelLayout);
        Input_panelLayout.setHorizontalGroup(
            Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Input_panelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Input_panelLayout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(Lbl_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Input_panelLayout.createSequentialGroup()
                        .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lbl_Format, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lbl_Born, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Txt_Day_Born, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Lbl_Document, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_DocumentStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126)
                        .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Input_panelLayout.createSequentialGroup()
                                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Input_panelLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(Lbl_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Txt_nameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Input_panelLayout.createSequentialGroup()
                                        .addComponent(Lbl_Grade)
                                        .addGap(18, 18, 18)
                                        .addComponent(Box_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lbl_section)
                                        .addGap(18, 18, 18)
                                        .addComponent(Box_section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(133, 133, 133)
                                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Lbl_LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Txt_LastNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Lbl_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Input_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(570, 570, 570)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        Input_panelLayout.setVerticalGroup(
            Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Input_panelLayout.createSequentialGroup()
                .addComponent(Lbl_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Input_panelLayout.createSequentialGroup()
                            .addComponent(Lbl_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Txt_nameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Input_panelLayout.createSequentialGroup()
                            .addComponent(Lbl_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Txt_LastNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Input_panelLayout.createSequentialGroup()
                        .addComponent(Lbl_Document, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_DocumentStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Input_panelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Lbl_Born, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Format, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_Day_Born, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lbl_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Input_panelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Lbl_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Box_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lbl_section, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Box_section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Input_panelLayout.createSequentialGroup()
                                .addComponent(Lbl_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84)
                        .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Input_panelLayout.createSequentialGroup()
                                .addComponent(Lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Input_panelLayout.createSequentialGroup()
                                .addComponent(Lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62)
                .addComponent(Btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        jPanel1.add(Input_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 767));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1637, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_nameStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_nameStudentMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nameStudentMousePressed

    private void Txt_nameStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_nameStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nameStudentActionPerformed

    private void Txt_LastNameStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_LastNameStudentMousePressed
        // Ingresar texto en Txt_username
        /*
        if (Txt_username.getText().equals("Ingrese nombre de usuario")) { //Si el nombre de usuario está vacío, se llenará con un mensaje en gris.

            Txt_username.setText("");
            Txt_username.setForeground(Color.black);//Al hacer clic, se despeja el campo y cambia el color de la fuente a negro
        }

        if (String.valueOf(Password_user.getPassword()).isEmpty()) {
            Password_user.setText("****************");
            Password_user.setForeground(Color.gray);
        }*/
    }//GEN-LAST:event_Txt_LastNameStudentMousePressed

    private void Txt_LastNameStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_LastNameStudentActionPerformed

    }//GEN-LAST:event_Txt_LastNameStudentActionPerformed

    private void Txt_Day_BornMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_Day_BornMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Day_BornMousePressed

    private void Txt_Day_BornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Day_BornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Day_BornActionPerformed

    private void Txt_DocumentStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_DocumentStudentMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DocumentStudentMousePressed

    private void Txt_DocumentStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DocumentStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DocumentStudentActionPerformed

    private void Btn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CreateActionPerformed
        // Accion del btn Crear
        
        Long id = Long.parseLong(Txt_DocumentStudent.getText());
        String nombre = Txt_nameStudent.getText();
        String apellido = Txt_LastNameStudent.getText();
        String fecha = Txt_Day_Born.getText();
        String sexo = "M";
        byte grado = Byte.parseByte(Box_grade.getSelectedItem().toString());
        String seccion = Box_section.getSelectedItem().toString();
        String direccion = Txt_Direction.getText();
        long telefono = Long.parseLong(Txt_telephone.getText());
        String email = Txt_email.getText();
        String contraseña = Txt_password.getText();
        String id_Curso = grado + seccion;
        
        try{
            
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO estudiantes (id_Alumno, Nombres, Apellidos, Fecha_Nacimiento, Sexo, Grado, Seccion ,Direccion, Telefono, Email, Contraseña, id_Curso) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
            
            ps.setLong(1, id);
            ps.setString(2, nombre);
            ps.setString(3, apellido);
            ps.setString(4, fecha);
            ps.setString(5,sexo);
            ps.setInt(6, grado);
            ps.setString(7, seccion);
            ps.setString(8, direccion);
            ps.setLong(9, telefono);
            ps.setString(10, email);
            ps.setString(11, contraseña);
            ps.setString(12, id_Curso);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro guardado");
            clean();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_Btn_CreateActionPerformed

    private void Txt_DirectionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_DirectionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DirectionMousePressed

    private void Txt_DirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DirectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DirectionActionPerformed

    private void Txt_telephoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_telephoneMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_telephoneMousePressed

    private void Txt_telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_telephoneActionPerformed

    private void Txt_emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_emailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_emailMousePressed

    private void Txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_emailActionPerformed

    private void Txt_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_passwordMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_passwordMousePressed

    private void Txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_passwordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box_grade;
    private javax.swing.JComboBox<String> Box_section;
    private javax.swing.JButton Btn_Create;
    private javax.swing.JPanel Input_panel;
    private javax.swing.JLabel Lbl_Born;
    private javax.swing.JLabel Lbl_Direction;
    private javax.swing.JLabel Lbl_Document;
    private javax.swing.JLabel Lbl_Email;
    private javax.swing.JLabel Lbl_Format;
    private javax.swing.JLabel Lbl_Grade;
    private javax.swing.JLabel Lbl_LastName;
    private javax.swing.JLabel Lbl_Name1;
    private javax.swing.JLabel Lbl_Student;
    private javax.swing.JLabel Lbl_Telephone;
    private javax.swing.JLabel Lbl_password;
    private javax.swing.JLabel Lbl_section;
    private javax.swing.JTextField Txt_Day_Born;
    private javax.swing.JTextField Txt_Direction;
    private javax.swing.JTextField Txt_DocumentStudent;
    private javax.swing.JTextField Txt_LastNameStudent;
    private javax.swing.JTextField Txt_email;
    private javax.swing.JTextField Txt_nameStudent;
    private javax.swing.JTextField Txt_password;
    private javax.swing.JTextField Txt_telephone;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
