/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Graficas;

/**
 *
 * @author Aprendiz
 */
public class Nuevo_Profesor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Nuevo_Profesor
     */
    public Nuevo_Profesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Input_panel = new javax.swing.JPanel();
        Lbl_Teacher = new javax.swing.JLabel();
        Lbl_Document = new javax.swing.JLabel();
        Txt_DocumentTeacher = new javax.swing.JTextField();
        Lbl_Name1 = new javax.swing.JLabel();
        Txt_nameTeacher = new javax.swing.JTextField();
        Lbl_LastName = new javax.swing.JLabel();
        Txt_LastNameTeacher = new javax.swing.JTextField();
        Lbl_Direction = new javax.swing.JLabel();
        Txt_Direction = new javax.swing.JTextField();
        Lbl_Telephone = new javax.swing.JLabel();
        Txt_telephone = new javax.swing.JTextField();
        Lbl_Email = new javax.swing.JLabel();
        Txt_email = new javax.swing.JTextField();
        Lbl_password = new javax.swing.JLabel();
        Txt_password = new javax.swing.JTextField();
        Btn_Create = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(1700, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Input_panel.setBackground(new java.awt.Color(255, 255, 255));
        Input_panel.setPreferredSize(new java.awt.Dimension(1600, 650));

        Lbl_Teacher.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Lbl_Teacher.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Teacher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Teacher.setText("Nuevo Profesor");

        Lbl_Document.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Document.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Document.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Document.setText("N. Documento");

        Txt_DocumentTeacher.setBackground(new java.awt.Color(235, 235, 235));
        Txt_DocumentTeacher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_DocumentTeacher.setForeground(new java.awt.Color(0, 0, 0));
        Txt_DocumentTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_DocumentTeacherMousePressed(evt);
            }
        });
        Txt_DocumentTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DocumentTeacherActionPerformed(evt);
            }
        });

        Lbl_Name1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Name1.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Name1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Name1.setText("Nombres");

        Txt_nameTeacher.setBackground(new java.awt.Color(235, 235, 235));
        Txt_nameTeacher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_nameTeacher.setForeground(new java.awt.Color(0, 0, 0));
        Txt_nameTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_nameTeacherMousePressed(evt);
            }
        });
        Txt_nameTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_nameTeacherActionPerformed(evt);
            }
        });

        Lbl_LastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_LastName.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_LastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_LastName.setText("Apellidos");

        Txt_LastNameTeacher.setBackground(new java.awt.Color(235, 235, 235));
        Txt_LastNameTeacher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_LastNameTeacher.setForeground(new java.awt.Color(0, 0, 0));
        Txt_LastNameTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_LastNameTeacherMousePressed(evt);
            }
        });
        Txt_LastNameTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_LastNameTeacherActionPerformed(evt);
            }
        });

        Lbl_Direction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Direction.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Direction.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Direction.setText("Dirección");

        Txt_Direction.setBackground(new java.awt.Color(235, 235, 235));
        Txt_Direction.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_Direction.setForeground(new java.awt.Color(0, 0, 0));
        Txt_Direction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_DirectionMousePressed(evt);
            }
        });
        Txt_Direction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DirectionActionPerformed(evt);
            }
        });

        Lbl_Telephone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Telephone.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Telephone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Telephone.setText("Teléfono");

        Txt_telephone.setBackground(new java.awt.Color(235, 235, 235));
        Txt_telephone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_telephone.setForeground(new java.awt.Color(0, 0, 0));
        Txt_telephone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_telephoneMousePressed(evt);
            }
        });
        Txt_telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_telephoneActionPerformed(evt);
            }
        });

        Lbl_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Email.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Email.setText("Email");

        Txt_email.setBackground(new java.awt.Color(235, 235, 235));
        Txt_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_email.setForeground(new java.awt.Color(0, 0, 0));
        Txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_emailMousePressed(evt);
            }
        });
        Txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_emailActionPerformed(evt);
            }
        });

        Lbl_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_password.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_password.setText("Contraseña");

        Txt_password.setBackground(new java.awt.Color(235, 235, 235));
        Txt_password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_password.setForeground(new java.awt.Color(0, 0, 0));
        Txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_passwordMousePressed(evt);
            }
        });
        Txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_passwordActionPerformed(evt);
            }
        });

        Btn_Create.setBackground(new java.awt.Color(0, 173, 0));
        Btn_Create.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Create.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Create.setText("Crear");
        Btn_Create.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Btn_Create.setBorderPainted(false);
        Btn_Create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Input_panelLayout = new javax.swing.GroupLayout(Input_panel);
        Input_panel.setLayout(Input_panelLayout);
        Input_panelLayout.setHorizontalGroup(
            Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Input_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(709, 709, 709))
            .addGroup(Input_panelLayout.createSequentialGroup()
                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Input_panelLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(Lbl_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Input_panelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Input_panelLayout.createSequentialGroup()
                                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_Document, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_DocumentTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126)
                                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Input_panelLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(Lbl_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Txt_nameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Lbl_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lbl_LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Txt_LastNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        Input_panelLayout.setVerticalGroup(
            Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Input_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Input_panelLayout.createSequentialGroup()
                            .addComponent(Lbl_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Txt_nameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Input_panelLayout.createSequentialGroup()
                            .addComponent(Lbl_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Txt_LastNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Input_panelLayout.createSequentialGroup()
                        .addComponent(Lbl_Document, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_DocumentTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131)
                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(Lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(Btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
        );

        jPanel1.add(Input_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 1280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1629, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_DocumentTeacherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_DocumentTeacherMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DocumentTeacherMousePressed

    private void Txt_DocumentTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DocumentTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DocumentTeacherActionPerformed

    private void Txt_nameTeacherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_nameTeacherMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nameTeacherMousePressed

    private void Txt_nameTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_nameTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nameTeacherActionPerformed

    private void Txt_LastNameTeacherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_LastNameTeacherMousePressed
        // Ingresar texto en Txt_username
        /*
        if (Txt_username.getText().equals("Ingrese nombre de usuario")) { //Si el nombre de usuario está vacío, se llenará con un mensaje en gris.

            Txt_username.setText("");
            Txt_username.setForeground(Color.black);//Al hacer clic, se despeja el campo y cambia el color de la fuente a negro
        }

        if (String.valueOf(Password_user.getPassword()).isEmpty()) {
            Password_user.setText("****************");
            Password_user.setForeground(Color.gray);
        }*/
    }//GEN-LAST:event_Txt_LastNameTeacherMousePressed

    private void Txt_LastNameTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_LastNameTeacherActionPerformed

    }//GEN-LAST:event_Txt_LastNameTeacherActionPerformed

    private void Txt_DirectionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_DirectionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DirectionMousePressed

    private void Txt_DirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DirectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DirectionActionPerformed

    private void Txt_telephoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_telephoneMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_telephoneMousePressed

    private void Txt_telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_telephoneActionPerformed

    private void Txt_emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_emailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_emailMousePressed

    private void Txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_emailActionPerformed

    private void Txt_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_passwordMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_passwordMousePressed

    private void Txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_passwordActionPerformed

    private void Btn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CreateActionPerformed

    }//GEN-LAST:event_Btn_CreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Create;
    private javax.swing.JPanel Input_panel;
    private javax.swing.JLabel Lbl_Direction;
    private javax.swing.JLabel Lbl_Document;
    private javax.swing.JLabel Lbl_Email;
    private javax.swing.JLabel Lbl_LastName;
    private javax.swing.JLabel Lbl_Name1;
    private javax.swing.JLabel Lbl_Teacher;
    private javax.swing.JLabel Lbl_Telephone;
    private javax.swing.JLabel Lbl_password;
    private javax.swing.JTextField Txt_Direction;
    private javax.swing.JTextField Txt_DocumentTeacher;
    private javax.swing.JTextField Txt_LastNameTeacher;
    private javax.swing.JTextField Txt_email;
    private javax.swing.JTextField Txt_nameTeacher;
    private javax.swing.JTextField Txt_password;
    private javax.swing.JTextField Txt_telephone;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
