/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Graficas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aprendiz
 */
public class Students extends javax.swing.JPanel {

    /**
     * Creates new form Students
     */
    JDesktopPane desktopPane = new JDesktopPane();

    public Students() {
        initComponents();

     

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/jdesktop.png"));
        Image image = icon.getImage();
        ventana = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        North_panel = new javax.swing.JPanel();
        btn_create = new javax.swing.JButton();
        btn_table = new javax.swing.JButton();
        btn_moficar = new javax.swing.JButton();
        Btn_Delete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setBackground(new java.awt.Color(255, 255, 255));

        ventana.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 0), 1, true));

        javax.swing.GroupLayout ventanaLayout = new javax.swing.GroupLayout(ventana);
        ventana.setLayout(ventanaLayout);
        ventanaLayout.setHorizontalGroup(
            ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1642, Short.MAX_VALUE)
        );
        ventanaLayout.setVerticalGroup(
            ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );

        North_panel.setOpaque(false);
        North_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_create.setBackground(new java.awt.Color(0, 173, 0));
        btn_create.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_create.setForeground(new java.awt.Color(255, 255, 255));
        btn_create.setText("Crear");
        btn_create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        North_panel.add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 150, 50));

        btn_table.setBackground(new java.awt.Color(0, 173, 0));
        btn_table.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_table.setForeground(new java.awt.Color(255, 255, 255));
        btn_table.setText("Ver Lista");
        btn_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tableActionPerformed(evt);
            }
        });
        North_panel.add(btn_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 150, 50));

        btn_moficar.setBackground(new java.awt.Color(0, 173, 0));
        btn_moficar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_moficar.setForeground(new java.awt.Color(255, 255, 255));
        btn_moficar.setText("Modificar");
        btn_moficar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_moficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moficarActionPerformed(evt);
            }
        });
        North_panel.add(btn_moficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 150, 50));

        Btn_Delete.setBackground(new java.awt.Color(0, 173, 0));
        Btn_Delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Delete.setText("Eliminar");
        Btn_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });
        North_panel.add(Btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 70, 150, 50));

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(North_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1650, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(ventana)
                .addContainerGap())
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(North_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 1280));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tableActionPerformed
        Table_Students table = new Table_Students();
        ventana.removeAll();

        ventana.add(table);
        ventana.revalidate();
        ventana.repaint();
        table.setVisible(true);
   

    }//GEN-LAST:event_btn_tableActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        Crear New_Student = new Crear();
        ventana.removeAll();
        ventana.add(New_Student);
        ventana.revalidate();
        ventana.repaint();
        New_Student.setVisible(true);
    }//GEN-LAST:event_btn_createActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void btn_moficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moficarActionPerformed
        // Modificar
 
    }//GEN-LAST:event_btn_moficarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Delete;
    private javax.swing.JPanel Container;
    private javax.swing.JPanel North_panel;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_moficar;
    private javax.swing.JButton btn_table;
    private javax.swing.JDesktopPane ventana;
    // End of variables declaration//GEN-END:variables

    private void setContentPane(JDesktopPane e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
